spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:account
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
